### ISSUE TITLE
Not functional?

### ISSUE THREAD

**Issue by theoephraim** [volarjs/pug-language-tools#4]
Was hoping to use pug on a new vue project and it seems that this plugin is not functional? It seems that intelisense is not working at all, and typescript is unable to realize that a component has been used (getting `'HelloWorld' is declared but its value is never read.` ts errors).

<img width="461" alt="image" src="https://github.com/volarjs/pug-language-tools/assets/1158956/a3bbb4bc-76ed-4fae-b5fb-9305871e8a4c">

To reproduce - install the extension, create a fresh vue/vite project, install pug and set lang="pug" on the template.

Am I missing some setup step? Or is this still plugin still a WIP? 

Thank you very much for all your work on volar and vue :)

**Comment by theoephraim** [comment]
ok I just discovered my error... I had assumed I needed this extension installed to get the IDE to understand pug within my vue templates, when it seems I actually just needed to install the vue language plugin - https://www.npmjs.com/package/@vue/language-plugin-pug 

I guess I am/was a bit confused about how all of the different tools and packages all relate to each other and was not clear on what is required in different scenarios. Probably the VSCode extension listing, and the readmes could all use a bit of clarification. I'm also curious you plan on moving the pug-related code out of https://github.com/volarjs/services and into this module?

related pages / readmes / repos:
- vue language pug plugin - https://www.npmjs.com/package/@vue/language-plugin-pug
- pug language tools (language server + vscode extension repo) - https://github.com/volarjs/pug-language-tools
- VSCode Extension listing ([extension marketplace](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.vscode-pug) 
- pug volar service - https://github.com/volarjs/services/tree/master/packages/pug

**Comment by johnsoncodehk** [comment]
This repo ([volarjs/pug-language-tools](https://github.com/volarjs/pug-language-tools) and [extension marketplace](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.vscode-pug)) is intended to provide language support for `.pug` files, not the pug template in `.vue`.

`@vue/language-plugin-pug`: This is used to parse the Vue pug template into a Vue template AST, rather than providing language support.

[volar-service-pug](https://github.com/volarjs/services/tree/master/packages/pug): This is the Pug language supported implementation, which is used by `@vue/language-service` and this repo.
